### ISSUE TITLE
Hvorfor nulle ut pot ved fold? 

### ISSUE THREAD

**Issue by mrminy** [SlayerFromNorth/Poker_G#2]
Hvorfor nuller du ut pot ved fold?
            status[1], status[2], status[3] = 0, 0, 0

**Comment by SlayerFromNorth** [comment]
Fordi den runden er ferdig, og alle pengene i potten den runden har blitt gitt til den som ikke foldet. Så da gjør den status lista klar til ny runde. Sånn at stauts lista blir [x spiller, 0, 0 ,0 , yspiller], og klar for ny runde.
